Feat/app demo
rees46/demo-android pull request #2
Opened 2024-07-03 16:27 UTC by xeewii

https://github.com/rees46/planning/issues/823

2024-07-05 09:09 UTC, TorinAsakura requested changes
Тут явно нужно разобрать работу со слоями @nelfimov

2024-07-05 09:45 UTC, Nelfimov requested changes
Код необходимо писать по FSD - https://feature-sliced.design/ru/docs/get-started/overview

Совсем вкратце - должно быть разделение по слоям. 
- `shared` - где ты складывешь переиспользуемое по всему приложению. Напр.:
  - `ui` - твои виджеты/компоненты
  - `theme` - тема приложения. Цвета, шрифты и проч стилистика
- `screens` - где уже полноценные экраны
- `app` - твой кор приложения. Роуты, зависимости и т.д.
- `features` - где у тебя переиспользуемая логика приложения 

Помимо этого надо четко разделять ответственность в коде. На примере виджета/компонента:
- отдельный файл для рендера виджета
- отдельный файл для логики - эвенты, расчеты и т.д.
- отдельный файл/слой для стилей - все то что придает стилистику виджету в зависимости от каких то параметров. Стили можно разделять на `base`, `appearance`, `shape`. Из названия понятно что куда.

По сути нужно следовать SOLID - создавать максимально унитарные и изолированные друг от друга куски кода, которые ты легко сможешь переиспользовать по приложению.

2024-07-05 09:47 UTC, Nelfimov commented
В качестве примера - скрин приложения на флаттере, который следовал FSD:

![image](https://github.com/rees46/demo-android/assets/44067768/8be9c8a4-5293-4bc9-ab0d-faea4dd47907)

2024-07-08 15:56 UTC, xeewii commented
@TorinAsakura сделала разделение по слоям, применимое к андроиду

2024-07-09 21:38 UTC, TorinAsakura commented
> @TorinAsakura сделала разделение по слоям, применимое к андроиду

полагаю, было бы неплохо прикладывать ридми, чтобы люди не морочились со сборкой/запуском как это делал я сейчас

2024-07-10 14:29 UTC, TorinAsakura requested changes
Надо созваниваться короче и проходиться/разбираться так как это вообще что-то не понятное

2024-07-10 14:29 UTC, TorinAsakura commented on app/src/main/java/rees46/demo_android/core/base/BaseFragment.kt
> +abstract class BaseFragment<VB : ViewBinding>(
Не понятно что такое "БазовыйФрагмент" - как он может относиться к бизнесу приложения/экрана

2024-07-10 14:29 UTC, TorinAsakura commented on app/src/main/java/rees46/demo_android/core/utils/FragmentExt.kt
> +internal val Fragment.windowInsetsController: WindowInsetsControllerCompat
Также требует пояснений

2024-07-10 14:29 UTC, TorinAsakura commented on app/src/main/java/rees46/demo_android/core/utils/ImageUtils.kt
> +    internal fun updateImage(rootView: View, imageView: ImageView, imageUrl: String) {
В целом про класс утилит, которые явно относятся к UI, могу спросить одно - почему они в core?

2024-07-10 14:29 UTC, TorinAsakura commented on app/src/main/java/rees46/demo_android/feature/cardProduct/CardProductFragment.kt
> +        binding.recommendationBlock.setHeaderText("You also may like")
хардкод локализации

2024-07-10 14:29 UTC, TorinAsakura commented on app/src/main/java/rees46/demo_android/feature/cardProduct/CardProductFragment.kt
> +    private fun setupViewModel() {
вообще не понимаю что такое фрагмент в твоём понимании

2024-07-10 14:29 UTC, TorinAsakura commented on app/src/main/java/rees46/demo_android/feature/cardProduct/CardProductView.kt
> +    fun setupCartController(onCartActionClick: (rees46.demo_android.domain.feature.card_product.CardAction) -> Unit) {
Я не понимаю как у тебя контроллер живёт во вью

2024-07-10 14:29 UTC, TorinAsakura commented on app/src/main/java/rees46/demo_android/feature/cardProduct/CardProductView.kt
> +class CardProductView @JvmOverloads constructor(
Почему у тебя КарточкаПродукта это фича?

2024-07-10 14:29 UTC, TorinAsakura commented on app/src/main/java/rees46/demo_android/feature/main/MainFragment.kt
> +class MainFragment
что такое "ГлавнаяФича"?

2024-07-14 22:32 UTC, xeewii commented on app/src/main/java/rees46/demo_android/core/base/BaseFragment.kt
> +abstract class BaseFragment<VB : ViewBinding>(
Это фрагмент для удобной работы с биндингом. Перенесла его в ui

2024-07-14 22:34 UTC, xeewii commented on app/src/main/java/rees46/demo_android/feature/cardProduct/CardProductView.kt
> +    fun setupCartController(onCartActionClick: (rees46.demo_android.domain.feature.card_product.CardAction) -> Unit) {
Неправильно назвала метод - нет никакого контроллера(
Это метод для настройки действий с корзиной, переименовала его

2024-07-14 22:42 UTC, xeewii commented on app/src/main/java/rees46/demo_android/feature/cardProduct/CardProductFragment.kt
> +    private fun setupViewModel() {
Мне кажется, ты здесь под КарточкойПродукта понимаешь карточку продукта, которую мы видим в списке рекомендаций или в каталоге и тд. Но этот фрагмент отвечает не за такую карточку, а за целый экран с описанием товара, возможностью добавить в корзину и тд. То есть это то, что откроется по нажатию на товар в блоке рекомендаций, например.
Из-за этого недопонимая вопрос возник?

2024-07-15 10:01 UTC, xeewii commented on app/src/main/java/rees46/demo_android/core/utils/ImageUtils.kt
> +    internal fun updateImage(rootView: View, imageView: ImageView, imageUrl: String) {
Убрала их из core в app слой

2024-07-15 10:19 UTC, xeewii commented on app/src/main/java/rees46/demo_android/feature/cardProduct/CardProductFragment.kt
> +        binding.recommendationBlock.setHeaderText("You also may like")
Изменила на данные, полученные из сдк

2024-07-15 10:28 UTC, xeewii commented on app/src/main/java/rees46/demo_android/feature/main/MainFragment.kt
> +class MainFragment
Этот фрагмент отвечает за взаимодействие других фрагментов

2024-07-15 10:29 UTC, xeewii commented on app/src/main/java/rees46/demo_android/core/utils/FragmentExt.kt
> +internal val Fragment.windowInsetsController: WindowInsetsControllerCompat
Эти расширения фрагмента нужны для скрытия bottom и top панелей при поиске.
Но в core ей не место - убрала

2024-07-15 10:30 UTC, xeewii commented on app/src/main/java/rees46/demo_android/feature/cardProduct/CardProductView.kt
> +class CardProductView @JvmOverloads constructor(
Ответ тот же про недопонимание в названии

2024-07-24 05:04 UTC, Nelfimov commented
@xeewii это уже можно смотреть?

2024-07-24 08:01 UTC, xeewii commented
> @xeewii это уже можно смотреть?

Думаю, стоит смотреть после @TorinAsakura

2024-07-24 15:24 UTC, TorinAsakura requested changes
В остальном коде проблемы имеют тот же характер: 
- неправильное использование шейредфлоу
- неправильное испоьльзование корутин
- фундаментальные/структурные проблемы в коде

2024-07-24 15:24 UTC, TorinAsakura commented on feature/src/main/java/rees46/demo_android/feature/home/presentation/view/HomeFragment.kt
> +            sdk.initializeStoriesView(this)
эээ, а зачем ты вызываешь его напрямую? как потом это дебажить?

2024-07-24 15:24 UTC, TorinAsakura commented on feature/src/main/java/rees46/demo_android/feature/home/presentation/view/HomeFragment.kt
> +            lifecycleScope.launch {
если фрагмент будет уничтожен до завершения работы корутин это вызовет утечку

2024-07-24 15:24 UTC, TorinAsakura commented on feature/src/main/java/rees46/demo_android/feature/home/presentation/viewmodel/HomeViewModel.kt
> +    companion object {
в конструктор

2024-07-24 15:24 UTC, TorinAsakura commented on feature/src/main/java/rees46/demo_android/feature/productDetails/di/ProductDetailsModule.kt
> +            product = product.get()
а если он не будет передан или передан не так как это ожидается?

2024-07-24 15:24 UTC, TorinAsakura commented on feature/src/main/java/rees46/demo_android/feature/productDetails/presentation/view/ProductDetailsFragment.kt
> +        lifecycleScope.launch {
снова кейс с корутинами, нужно запускаться через viewLifecycleOwner.lifecycleScope

2024-07-24 15:24 UTC, TorinAsakura commented on feature/src/main/java/rees46/demo_android/feature/productDetails/presentation/viewmodel/ProductDetailsViewModel.kt
> +    private val _recommendationFlow: MutableSharedFlow<Recommendation> = MutableSharedFlow(replay = 1)
снова шейреды

2024-07-24 15:24 UTC, TorinAsakura commented on feature/src/main/java/rees46/demo_android/feature/productDetails/presentation/viewmodel/ProductDetailsViewModel.kt
> +    companion object {
то же что и предыдущей вьюмодели

2024-07-24 15:25 UTC, TorinAsakura commented
@Nelfimov с тебя потом пробежаться после её правок и проверить структуры на соответствие архитектуре

2024-07-25 11:54 UTC, xeewii commented on app/src/main/java/rees46/demo_android/app/di/AppModule.kt
> +            activity
Видимо изначально тут activity передавала и забыла переименовать по итогу(
Переименовала

2024-07-25 11:55 UTC, xeewii commented
Обновила версию java до 22, kotlin до 2.0.0 и gradle до 8.8

2024-07-25 14:14 UTC, xeewii commented on feature/src/main/java/rees46/demo_android/feature/cart/presentation/viewmodel/CartViewModel.kt
> +    val cartProductsFlow: Flow<MutableList<CartProduct>> = _cartProductsFlow
Изменила на MutableStateFlow, вынесла это в Cart

2024-07-25 14:18 UTC, xeewii commented on feature/src/main/java/rees46/demo_android/feature/cart/domain/repository/CartRepository.kt
> +    fun getSumPrice(): MutableStateFlow<Double>
Наружу везде вынесла Flow

2024-07-25 14:19 UTC, xeewii commented on feature/src/main/java/rees46/demo_android/feature/cart/domain/usecase/GetCartSumPriceUseCase.kt
> +    fun execute(): MutableSharedFlow<Double> =
Изменила просто на Flow

2024-07-25 14:20 UTC, xeewii commented on feature/src/main/java/rees46/demo_android/feature/productDetails/presentation/viewmodel/ProductDetailsViewModel.kt
> +    private val _recommendationFlow: MutableSharedFlow<Recommendation> = MutableSharedFlow(replay = 1)
Заменила на State

2024-07-25 14:22 UTC, xeewii commented
@TorinAsakura заменила SharedFlow на StateFlow

2024-07-25 14:33 UTC, xeewii commented on core/src/main/java/rees46/demo_android/core/utils/ImageUtils.kt
> +        Glide.with(rootView)
Объясни, пожалуйста, почему? 
Так как в object классе?

Изменила на функцию расширения для ImageView

2024-07-25 14:33 UTC, xeewii commented on core/src/main/java/rees46/demo_android/core/utils/ImageUtils.kt
> +    fun updateImage(rootView: View, imageView: ImageView, imageUrl: String) {
Изменила на функцию расширения для ImageView

2024-07-25 15:14 UTC, xeewii commented on feature/src/main/java/rees46/demo_android/feature/cart/data/api/CartApi.kt
> +            event = Params.TrackEvent.REMOVE_FROM_CART,
И правда про него забыла(
Добавила productId и коллбэк

2024-07-25 15:22 UTC, xeewii commented on feature/src/main/java/rees46/demo_android/feature/cart/di/CartModule.kt
> +    }
Добавила создание Cart отдельно, здесь его просто инджекчу

2024-07-25 15:27 UTC, xeewii commented on feature/src/main/java/rees46/demo_android/feature/cart/data/repository/CartRepositoryImpl.kt
> +    override fun addProduct(product: Product, quantity: Int) {
Добавила коллбек в CartApi, теперь добавление/удаление в Cart происходит только при успешном завершении

2024-07-25 15:41 UTC, TorinAsakura commented
> @TorinAsakura заменила SharedFlow на StateFlow, также исправила другие замечания, на которые отписалась

там куча вопросов остались без ответов

2024-07-25 15:42 UTC, xeewii commented
> > @TorinAsakura заменила SharedFlow на StateFlow, также исправила другие замечания, на которые отписалась
> 
> 
> 
> там куча вопросов остались без ответов

Да, просто ты говорил частями на ревью отправлять)
Вот я и сделала часть и отписала где и что именно)

2024-07-25 15:50 UTC, xeewii commented on feature/src/main/java/rees46/demo_android/feature/home/presentation/view/HomeFragment.kt
> +            lifecycleScope.launch {
Заменила lifecycleScope на viewLifecycleOwner.lifecycleScope

2024-07-25 16:21 UTC, xeewii commented on app/src/main/java/rees46/demo_android/app/presentation/MainActivity.kt
> +    private val navigator by lazy {
Потому что в этот момент вью ещё не инициализирована, а нужно получить navHostFragment через R

2024-07-25 17:11 UTC, xeewii commented on core/src/main/java/rees46/demo_android/core/utils/SdkUtils.kt
> +    fun initialize(sdk: SDK, context: Context, shopId: String? = SHOP_ID) {
Изменила во многих местах

2024-07-25 17:12 UTC, xeewii commented on app/src/main/java/rees46/demo_android/app/presentation/MainActivity.kt
> +                    with(binding.bottomNavigation) {
Да, хорошо бы смотрелось)
Вынесла

2024-07-25 17:20 UTC, xeewii commented on core/src/main/java/rees46/demo_android/core/utils/FragmentUtils.kt
> +    requireActivity().onBackPressedDispatcher.addCallback(object : OnBackPressedCallback(isEnabledBackButton) {
И правда(
Вообще удалила метод за ненадобностью

2024-07-25 17:21 UTC, xeewii commented on core/src/main/java/rees46/demo_android/core/utils/FragmentUtils.kt
> +fun Fragment.onBackPressedNavigation() {
Удалила метод за ненадобностью

2024-07-26 10:07 UTC, xeewii commented on core/src/main/java/rees46/demo_android/core/di/SdkModule.kt
> +            SDK().apply {
Перенесла инициализацию SDK в DemoApplication

2024-07-26 11:08 UTC, xeewii commented on feature/src/main/java/rees46/demo_android/feature/cart/data/models/Cart.kt
> +    var cartSumPrice: MutableStateFlow<Double> = MutableStateFlow(0.0)
Переделала на обновление по списку продуктов

2024-07-26 11:09 UTC, xeewii commented on feature/src/main/java/rees46/demo_android/feature/cart/data/models/Cart.kt
> +    fun addProduct(product: Product, quantity: Int) {
Не уверена, какой вариант ты хотел предложить, но что-то попыталась сделать)

2024-07-26 11:12 UTC, xeewii commented on feature/src/main/java/rees46/demo_android/feature/cart/presentation/adapter/CartProductsAdapter.kt
> +        notifyDataSetChanged()
А, точно, убрала

2024-07-26 11:13 UTC, xeewii commented on feature/src/main/java/rees46/demo_android/feature/home/presentation/view/HomeFragment.kt
> +            sdk.initializeStoriesView(this)
А как иначе вызывать? Если нужно инициализировать блок сторисов в сдк?)

2024-07-26 11:24 UTC, xeewii commented on feature/src/main/java/rees46/demo_android/feature/productDetails/di/ProductDetailsModule.kt
> +            product = product.get()
А что делать в таком случае? 
Могу показать окно с ошибкой просто, то есть только во вью обработать это или нужно где-то ещё?

2024-07-26 11:38 UTC, xeewii commented on core/src/main/java/rees46/demo_android/core/utils/SdkUtils.kt
> +    private const val SHOP_ID = "357382bf66ac0ce2f1722677c59511"
Хороший вопрос...
Создала отдельный класс SdkSettings для хранения настроек

2024-07-26 11:46 UTC, xeewii commented on feature/src/main/java/rees46/demo_android/feature/home/presentation/viewmodel/HomeViewModel.kt
> +    companion object {
Добавила код рекомендаций в конструктор, а сами коды храню теперь в core.settings.RecommendationSettings

2024-07-26 11:46 UTC, xeewii commented on feature/src/main/java/rees46/demo_android/feature/productDetails/presentation/viewmodel/ProductDetailsViewModel.kt
> +    companion object {
Добавила код рекомендаций в конструктор, а сами коды храню теперь в core.settings.RecommendationSettings

2024-07-29 19:12 UTC, TorinAsakura commented on feature/src/main/java/rees46/demo_android/feature/productDetails/di/ProductDetailsModule.kt
> +            product = product.get()
> А что делать в таком случае? Могу показать окно с ошибкой просто, то есть только во вью обработать это или нужно где-то ещё?

Вероятно нужно сделать проверку, да?

2024-07-29 19:16 UTC, TorinAsakura commented on feature/src/main/java/rees46/demo_android/feature/cart/presentation/viewmodel/CartViewModel.kt
> +    val cartProductsFlow: Flow<MutableList<CartProduct>> = _cartProductsFlow
Зачем тут мутейбл? Я писал про СтейтФлоу не просто так

2024-07-29 19:17 UTC, TorinAsakura commented on feature/src/main/java/rees46/demo_android/feature/cart/domain/usecase/GetCartSumPriceUseCase.kt
> +    fun execute(): MutableSharedFlow<Double> =
Да почему просто флоу если тут стейт тоже должен быть?

2024-07-29 19:19 UTC, TorinAsakura commented on feature/src/main/java/rees46/demo_android/feature/home/presentation/view/HomeFragment.kt
> +            sdk.initializeStoriesView(this)
Добавить проверки на жизненный цикл фрагмента при запуске корутин?

2024-07-29 19:21 UTC, TorinAsakura commented on app/src/main/java/rees46/demo_android/app/presentation/MainActivity.kt
> +    private val navigator by lazy {
а проблем с жизненным циклом не будет?

2024-07-29 19:24 UTC, TorinAsakura requested changes
последние строки в некоторых файлах и последние комменты порешать

2024-07-29 19:24 UTC, TorinAsakura commented on app/build.gradle.kts
>  }
последняя строка!

2024-07-29 19:24 UTC, TorinAsakura commented on core/src/main/java/rees46/demo_android/core/utils/ImageUtils.kt
> +    Glide.with(rootView)
я бы оказался от глайда

2024-07-29 19:25 UTC, xeewii commented on core/src/main/java/rees46/demo_android/core/utils/ImageUtils.kt
> +    Glide.with(rootView)
В пользу чего? Пикассо?

2024-07-30 08:41 UTC, TorinAsakura commented on core/src/main/java/rees46/demo_android/core/utils/ImageUtils.kt
> +    Glide.with(rootView)
> В пользу чего? Пикассо? Или как-то ручками?

ручками

2024-07-30 13:42 UTC, xeewii commented on feature/src/main/java/rees46/demo_android/feature/cart/presentation/viewmodel/CartViewModel.kt
> +    val cartProductsFlow: Flow<MutableList<CartProduct>> = _cartProductsFlow
Flow заменила на StateFlow.
Но Mutable же всё равно нужен, чтобы эммитить туда данные

2024-07-30 13:45 UTC, xeewii commented on feature/src/main/java/rees46/demo_android/feature/cart/domain/usecase/GetCartSumPriceUseCase.kt
> +    fun execute(): MutableSharedFlow<Double> =
Казалось так будет лучше, ибо высокоуровневее... Углублюсь в эту тему подробнее.

Заменила на StateFlow

2024-07-30 13:48 UTC, xeewii commented on core/src/main/java/rees46/demo_android/core/utils/ImageUtils.kt
> +    Glide.with(rootView)
Но Glide в зависимостях всё равно останется, ибо он у нас используется в SDK в сторисах.
Скорее всего нужно будет завести задачу, чтобы и от туда его убрать

2024-07-30 15:03 UTC, TorinAsakura commented on feature/src/main/java/rees46/demo_android/feature/home/presentation/view/HomeFragment.kt
> +            sdk.initializeStoriesView(this)
?

2024-07-30 15:03 UTC, TorinAsakura commented on core/src/main/java/rees46/demo_android/core/utils/ImageUtils.kt
> +    Glide.with(rootView)
> Но Glide в зависимостях всё равно останется, ибо он у нас используется в SDK в сторисах. Скорее всего нужно будет завести задачу, чтобы и от туда его убрать

оставь тогда, господь бы с ним, но, смотри что эта тварь не подтекала

2024-07-31 11:45 UTC, xeewii commented on feature/src/main/java/rees46/demo_android/feature/home/presentation/view/HomeFragment.kt
> +            sdk.initializeStoriesView(this)
Так я запускаю это в  onViewCreated().
Тогда уж лучше без функции это просто там написать, как с блоками рекомендаций там же?

2024-07-31 11:59 UTC, xeewii commented on app/build.gradle.kts
>  }
Добавила последние строки везде, где пропустила

2024-07-31 12:03 UTC, xeewii commented on core/src/main/java/rees46/demo_android/core/utils/ImageUtils.kt
> +    Glide.with(rootView)
Оставила

2024-07-31 12:56 UTC, TorinAsakura commented on feature/src/main/java/rees46/demo_android/feature/home/presentation/view/HomeFragment.kt
> +            sdk.initializeStoriesView(this)
> Так я запускаю это в onViewCreated(). Тогда уж лучше без функции это просто там написать, как с блоками рекомендаций там же?

да

2024-07-31 13:11 UTC, xeewii commented on feature/src/main/java/rees46/demo_android/feature/home/presentation/view/HomeFragment.kt
> +            sdk.initializeStoriesView(this)
Перенесла это блок в onViewCreated

2024-07-31 13:28 UTC, xeewii commented
Извиняюсь за последние два коммита после отправки на ревью.
Я просто вспомнила замечание из ревью по сдк насчет именования enum - это первый коммит.
А второй - вынесла незамеченный  RecommendedCode из CartViewModel в класс RecommendationSettings.
Совсем небольшие именения(

2024-07-31 13:28 UTC, TorinAsakura requested changes
Следующий этап это формирование изолированного UI слоя по канонам. Чтобы не расписывать всё то, что я уже расписывал, вот ссылка на аналогичное ревью в iOS демо репе https://github.com/rees46/demo-ios/pull/1#pullrequestreview-2207987673

2024-07-31 13:28 UTC, TorinAsakura commented on core/src/main/java/rees46/demo_android/core/utils/ViewUtils.kt
> +object ViewUtils {
не надо обзывать кучу утилит как УтилитыДляВсего - utilities - прежде всего паттерн, как и все прочие, значит должна быть структура вида

- core
-- utils
--- DpToPixel.utility.kt


Самое тут главное, чтобы утилита имела контекст, а то утилита вроде вьюшная, а находится в коре…не понятно

2024-07-31 13:28 UTC, TorinAsakura commented on feature/src/main/java/rees46/demo_android/feature/Navigator.kt
> +package rees46.demo_android.feature
чот не очень понял, а что это за фича Навигатор? И почему без собственного модуля, а просто файлом валяется?

2024-07-31 13:28 UTC, TorinAsakura commented on feature/src/main/java/rees46/demo_android/feature/productDetails/presentation/ProductAction.kt
> +enum class ProductAction {
Что за экшены? И почему нет конвенционального нейминга? Должно быть вида ProductSome.enum.kt

2024-07-31 13:31 UTC, xeewii commented on feature/src/main/java/rees46/demo_android/feature/Navigator.kt
> +package rees46.demo_android.feature
Это просто интерфейс для работы с навигатором из app во feature. Поэтому не стала его выносить в отдельную фичу. Подскажи, пожалуйста, куда пристроить его правильно?

2024-07-31 13:32 UTC, xeewii commented on feature/src/main/java/rees46/demo_android/feature/productDetails/presentation/ProductAction.kt
> +enum class ProductAction {
Вспомнила под конец только, уже поправлено

2024-08-01 19:57 UTC, TorinAsakura commented on feature/src/main/java/rees46/demo_android/feature/Navigator.kt
> +package rees46.demo_android.feature
что за навигатор? что за фича? контекста насыпь чтобы я обратно не погружался

2024-08-05 01:12 UTC, xeewii commented
> Следующий этап это формирование изолированного UI слоя по канонам. Чтобы не расписывать всё то, что я уже расписывал, вот ссылка на аналогичное ревью в iOS демо репе [rees46/demo-ios#1 (review)](https://github.com/rees46/demo-ios/pull/1#pullrequestreview-2207987673)

Не все правки еще внесла, но хотелось бы понять, в правильном ли направление движусь вообще, какие замечания сразу, чтобы сделать быстрее и правильнее. 
В общем в ui я пока вынесла recyclerView, buttons и countCard (это элемент, где счетчик, который можно менять по + и -).
В recyclerView создала базовые элементы списка, в котором вся логика. И для нужных мне списков наследовалась от них. Например, адаптер стал будто фабрикой, в которой я просто создаю нужный элемент, а подключение, биндинг и тд уже происходит одинаково в базовом адаптере. Так же эти отдельные списки вынесла тоже в ui (хотя может стоило оставить в фичах, где они и были).
Кнопки также одинаковые для всего проекта, настраивать их там тоже можно.
Это если короткое описание, так я эти изменения залила и заиспользовала.

Правильно ли делаю, или как нужно всё-таки? На примеры опиралась, но может не так адаптировала их(

2024-08-05 01:21 UTC, xeewii commented on feature/src/main/java/rees46/demo_android/feature/Navigator.kt
> +package rees46.demo_android.feature
Была проблема:
Граф навигации находится в app модуле, у меня там генерятся всякие directions для навигации. Мне нужно было воспользоваться ими для навигации из feature модуля? Получается циклическая зависимость.

Для этого я создала интерфейс навигатора в модуле features, и через него спокойно навигируюсь.
Это вроде не отдельная фича, но нужный интерфейс в этом модуле. Куда его тогда правильнее положить?

2024-08-05 15:54 UTC, xeewii commented on core/src/main/java/rees46/demo_android/core/utils/ViewUtils.kt
> +object ViewUtils {
разнесла утилиты, переименовала, и отделила utils от extensions

2024-08-06 14:30 UTC, TorinAsakura commented
> > Следующий этап это формирование изолированного UI слоя по канонам. Чтобы не расписывать всё то, что я уже расписывал, вот ссылка на аналогичное ревью в iOS демо репе [rees46/demo-ios#1 (review)](https://github.com/rees46/demo-ios/pull/1#pullrequestreview-2207987673)
> 
> @TorinAsakura Не все правки еще внесла, но хотелось бы понять, в правильном ли направление движусь вообще, какие замечания сразу, чтобы сделать быстрее и правильнее.
> 
> В общем в ui я пока вынесла recyclerView, buttons и countCard (это элемент, где счетчик, который можно менять по + и -). В recyclerView создала базовые элементы списка, в котором вся логика. И для нужных мне списков наследовалась от них. Например, адаптер стал будто фабрикой, в которой я просто создаю нужный элемент, а подключение, биндинг и тд уже происходит одинаково в базовом адаптере. Так же эти отдельные списки вынесла тоже в ui (хотя может стоило оставить в фичах, где они и были). Кнопки также одинаковые для всего проекта, настраивать их там тоже можно.
> 
> Это если короткое описание, так я эти изменения залила и заиспользовала. Правильно ли делаю, или как нужно всё-таки? На примеры опиралась, но может не так адаптировала их(

Я тебе дал исчерпывающий пример к имплементации. Сейчас из всего что ты сделала правильным является только вынос кнопок, да и то пока я не видел как ты их вынесла

2024-08-06 21:32 UTC, TorinAsakura commented on feature/src/main/java/rees46/demo_android/feature/Navigator.kt
> +package rees46.demo_android.feature
> Была проблема: Граф навигации находится в app модуле, у меня там генерятся всякие directions для навигации. Мне нужно было воспользоваться ими для навигации из feature модуля. Получается циклическая зависимость.
> 
> Для этого я создала интерфейс навигатора в модуле features, и через него спокойно навигируюсь. Это вроде не отдельная фича, но нужный интерфейс в этом модуле. Куда его тогда правильнее положить?

```tree
app
├── src
├── build.gradle
core
├── src
├── build.gradle
navigation
├── src
│   └── main
│       └── java
│           └── rees46
│               └── demo_android
│                   └── navigation
│                       ├── Navigator.kt
│                       └── Destination.kt
├── build.gradle
feature
├── src
├── build.gradle
```

1. Создай отдельный модуль навигации, который будет содержать интерфейс Navigator и все связанные с ним данные. Этот модуль может быть зависим от модуля app, но не от feature.
2. Этот интерфейс должен быть в модуле, который является общим для всех остальных модулей, в данном случае в модуле navigation
3. Модуль feature будет использовать интерфейс Navigator, но не будет напрямую зависеть от модуля app

2024-08-06 21:57 UTC, TorinAsakura requested changes

2024-08-06 21:57 UTC, TorinAsakura commented on feature/src/main/res/values/dimens.xml
что такое dimens? 
1. Не сокращай - не усложняй другим работу, и так большой объём данных
2. Разбирай на скоупы, иначе твой ресурс превратится в кашу, опять же - смотри гиперион

2024-08-06 21:57 UTC, TorinAsakura commented on ui/src/main/java/com/rees46/demo_android/ui/button/view/CommonBlackButton.kt
> +open class CommonBlackButton @JvmOverloads constructor(
так, это вот хреновая практика, ты сейчас только что убила всю соль декомпозиции прибив к кнопке именем чёрный цвет, а если завтра мы сменим цвет, что, будешь переделывать всё? Ты должна определять цвет по месту использования, а не в месте инициализации - опять же…смотри в гиперион

2024-08-06 21:57 UTC, TorinAsakura commented on ui/src/main/java/com/rees46/demo_android/ui/recyclerView/base/models/Item.kt
> +abstract class Item {
что такое Item?) Давай хотя бы RecyclerViewItem - а то вообще мрак)

2024-08-06 21:57 UTC, TorinAsakura commented on ui/src/main/java/com/rees46/demo_android/ui/recyclerView/search/view/adapter/SearchCategoryAdapter.kt
А давай адаптер не будет являться частью view?

Полагаю это должно быть как-то так
```tree
src
└── main
    ├── java
    │   └── com
    │       └── rees46
    │           └── demo_android
    │               ├── search
    │               │   ├── adapter
    │               │   │   └── SearchCategoryAdapter.kt
    │               │   ├── model
    │               │   │   └── SearchCategory.kt
    │               │   └── view
    │               │       └── SearchCategoryFragment.kt
    │               └── cart
    │                   ├── adapter
    │                   │   └── CartAdapter.kt
    │                   ├── model
    │                   │   └── CartItem.kt
    │                   └── view
    │                       └── CartFragment.kt
    └── res
        ├── layout
        │   ├── fragment_search_category.xml
        │   └── fragment_cart.xml
        ├── values
        │   ├── strings.xml
        │   └── dimens.xml
```

2024-08-06 21:57 UTC, TorinAsakura commented on ui/src/main/java/com/rees46/demo_android/ui/utils/DimensionsConverter.utils.kt
> +    fun convertResToPx(
TypedValue? Не?

2024-08-06 21:57 UTC, TorinAsakura commented on ui/src/main/java/com/rees46/demo_android/ui/utils/ViewColor.utils.kt
1. ContextCompat.getColor
2. View.setBackgroundColor
3. TextView.setTextColor
4. Color.parseColor

Не?

2024-08-06 21:57 UTC, TorinAsakura commented on ui/src/main/java/com/rees46/demo_android/ui/button/view/CommonButton.kt
никаких каммонов - уже говорил тебе, что как только ты начинаешь плодить всякие каммоны - ты тут же стреляешь себе в ногу так как потом этот каммон станет огромным и монструозным и тебе по итогу, когда он разрастётся на 1к+ строк придётся его разделять

2024-08-07 19:24 UTC, xeewii commented on ui/src/main/java/com/rees46/demo_android/ui/button/view/CommonButton.kt
Сделала просто кнопку с настройками

2024-08-07 19:24 UTC, xeewii commented on ui/src/main/java/com/rees46/demo_android/ui/utils/ViewColor.utils.kt
Разнесла по функциям расширения

2024-08-07 19:26 UTC, xeewii commented on ui/src/main/java/com/rees46/demo_android/ui/utils/DimensionsConverter.utils.kt
> +    fun convertResToPx(
Там много всего нужно писать, чтобы ресурсы привести к нужному виду - сделала намного лаконичнее в Context.extenstions.kt

2024-08-07 19:26 UTC, xeewii commented on ui/src/main/java/com/rees46/demo_android/ui/recyclerView/search/view/adapter/SearchCategoryAdapter.kt
Убрала адаптер из вью

2024-08-07 19:26 UTC, xeewii commented on ui/src/main/java/com/rees46/demo_android/ui/recyclerView/base/models/Item.kt
> +abstract class Item {
Хорошо)

2024-08-07 19:27 UTC, xeewii commented on ui/src/main/java/com/rees46/demo_android/ui/button/view/CommonBlackButton.kt
> +open class CommonBlackButton @JvmOverloads constructor(
Разнесла кнопки по их использованию со своими настройками

2024-08-07 19:28 UTC, xeewii commented on feature/src/main/res/values/dimens.xml
dimens - так принято в android просто...
Разделила на несколько файлов по использованию

2024-08-07 19:29 UTC, xeewii commented on feature/src/main/java/rees46/demo_android/feature/Navigator.kt
> +package rees46.demo_android.feature
Сделала отдельный модуль навигации

2024-08-07 21:20 UTC, TorinAsakura commented on app/src/main/java/rees46/demo_android/core/utils/ImageUtils.kt
> +    internal fun updateImage(rootView: View, imageView: ImageView, imageUrl: String) {
> Убрала их из core в app слой

а почему арр-то если это юай? до всех пор не понятно

2024-08-07 21:24 UTC, merged