feat: Change config to using publish from workflow
rees46/demo-android pull request #9
Opened 2024-10-17 14:53 UTC by DanielGreenEngineer

- https://github.com/rees46/planning/issues/1838

2024-10-17 16:49 UTC, Nelfimov requested changes
решение по этому ПР будет в зависимости от https://github.com/rees46/workflow/pull/242#discussion_r1805106509

2024-10-29 15:13 UTC, DanielGreenEngineer commented
@Nelfimov Тут нужно что-то менять исходя из основного экшена?

2024-10-30 07:30 UTC, Nelfimov requested changes

2024-10-30 07:30 UTC, Nelfimov commented on .github/workflows/publish.yaml
> +    uses: rees46/workflow/.github/workflows/reusable-android-demo-shop-publish.yml@master
такого экшена нет же в репе `workflow`

2024-10-30 07:30 UTC, Nelfimov commented on .github/workflows/publish.yaml
> +      GITHUB_APP_ID: ${{ secrets.PUBLIVERSIONER_ID }}
тут не секрет а vars

2024-10-30 08:19 UTC, DanielGreenEngineer commented on .github/workflows/publish.yaml
> +    uses: rees46/workflow/.github/workflows/reusable-android-demo-shop-publish.yml@master
Забыл о том, что переименовал его. 
Заменил на актуальный.

2024-10-30 08:21 UTC, DanielGreenEngineer commented on .github/workflows/publish.yaml
> +      GITHUB_APP_ID: ${{ secrets.PUBLIVERSIONER_ID }}
Какие поля на vars заменить? В demo-ios же аналогично всё в секретах.

2024-10-30 08:33 UTC, Nelfimov commented on .github/workflows/publish.yaml
> +      GITHUB_APP_ID: ${{ secrets.PUBLIVERSIONER_ID }}
на чем коммент оставил, `PUBLIVERSIONER_ID`

<img width="807" alt="image" src="https://github.com/user-attachments/assets/3e953bd8-2426-423c-a631-9fcefcd0df58">

`demo-ios` - проглядел

2024-10-30 08:35 UTC, DanielGreenEngineer commented on .github/workflows/publish.yaml
> +      GITHUB_APP_ID: ${{ secrets.PUBLIVERSIONER_ID }}
Понял. IOS сейчас тоже сменю.

2024-10-30 08:58 UTC, Nelfimov approved these changes

2024-10-30 08:58 UTC, merged